import type { Screening } from "@/types/screening";

export async function generateScreeningPDF(screening: Screening, userEmail?: string) {
  const { jsPDF } = await import("jspdf");
  const { default: autoTable } = await import("jspdf-autotable");
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFontSize(20);
  doc.setTextColor(30, 58, 95); // primary #1E3A5F
  doc.text("AllClear", 14, 20);

  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139); // text-secondary
  doc.text("Sanctions Screening Report", 14, 27);

  // Divider
  doc.setDrawColor(226, 232, 240); // border
  doc.line(14, 30, pageWidth - 14, 30);

  // Meta info
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42); // text-primary
  const metaY = 38;
  doc.text(`Query: ${screening.query}`, 14, metaY);
  doc.text(
    `Date: ${new Date(screening.created_at).toLocaleString()}`,
    14,
    metaY + 7
  );
  doc.text(
    `Status: ${screening.status === "clear" ? "CLEAR" : "FLAGGED"}`,
    14,
    metaY + 14
  );
  doc.text(`Matches: ${screening.match_count}`, 14, metaY + 21);
  if (userEmail) {
    doc.text(`Screened by: ${userEmail}`, 14, metaY + 28);
  }

  // Results table
  if (
    screening.result_snapshot.results &&
    screening.result_snapshot.results.length > 0
  ) {
    const tableData = screening.result_snapshot.results.map((r) => [
      r.caption,
      r.schema,
      (r.properties.country || []).join(", ") || "—",
      r.datasets.join(", "),
      `${Math.round(r.score * 100)}%`,
    ]);

    autoTable(doc, {
      startY: metaY + (userEmail ? 36 : 28),
      head: [["Entity", "Type", "Countries", "Datasets", "Score"]],
      body: tableData,
      styles: { fontSize: 8, cellPadding: 3 },
      headStyles: {
        fillColor: [30, 58, 95],
        textColor: 255,
        fontStyle: "bold",
      },
      columnStyles: {
        0: { cellWidth: 40 },
        3: { cellWidth: 55 },
      },
    });
  }

  // Datasets checked footer
  const finalY = (doc as InstanceType<typeof jsPDF> & { lastAutoTable?: { finalY: number } })
    .lastAutoTable?.finalY ?? (metaY + 40);

  if (
    screening.result_snapshot.datasets &&
    screening.result_snapshot.datasets.length > 0
  ) {
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);
    doc.text("Datasets checked:", 14, finalY + 10);
    const datasetNames = screening.result_snapshot.datasets
      .map((d) => d.title || d.name)
      .join(", ");
    const lines = doc.splitTextToSize(datasetNames, pageWidth - 28);
    doc.text(lines, 14, finalY + 17);
  }

  // Footer
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text(
    `Generated by AllClear on ${new Date().toLocaleString()} — This report is a point-in-time screening and does not constitute legal advice.`,
    14,
    pageHeight - 10
  );

  return doc;
}
