"use client";

import type { Screening, Country } from "@/types/screening";
import { Badge } from "@/components/ui/Badge";

interface ScreeningReportProps {
  screening: Screening;
  userEmail?: string;
  countries: Map<string, Country>;
}

export function ScreeningReport({ screening, userEmail, countries }: ScreeningReportProps) {
  const results = screening.result_snapshot.results || [];
  const datasets = screening.result_snapshot.datasets || [];

  return (
    <div className="mx-auto max-w-3xl bg-white p-8 print:p-4">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-border-col pb-4">
        <div>
          <h1 className="font-heading text-2xl font-bold text-primary">AllClear</h1>
          <p className="text-sm text-text-secondary">Sanctions Screening Report</p>
        </div>
        <div className="text-right text-sm text-text-secondary">
          <p>{new Date(screening.created_at).toLocaleString()}</p>
          {userEmail && <p>{userEmail}</p>}
        </div>
      </div>

      {/* Meta */}
      <div className="mt-6 grid grid-cols-2 gap-4">
        <div>
          <p className="text-xs font-semibold uppercase text-text-secondary">Query</p>
          <p className="mt-1 text-lg font-heading font-semibold text-text-primary">
            {screening.query}
          </p>
        </div>
        <div>
          <p className="text-xs font-semibold uppercase text-text-secondary">Status</p>
          <div className="mt-1">
            <Badge variant={screening.status === "clear" ? "clear" : "flagged"}>
              {screening.status === "clear" ? "All Clear" : `${screening.match_count} Match${screening.match_count !== 1 ? "es" : ""} Found`}
            </Badge>
          </div>
        </div>
      </div>

      {/* Results Table */}
      {results.length > 0 && (
        <div className="mt-8">
          <h2 className="font-heading text-sm font-semibold uppercase text-text-secondary mb-3">
            Screening Results
          </h2>
          <table className="w-full text-sm border border-border-col">
            <thead>
              <tr className="bg-primary text-white text-left">
                <th className="px-3 py-2 font-semibold">Entity</th>
                <th className="px-3 py-2 font-semibold">Type</th>
                <th className="px-3 py-2 font-semibold">Countries</th>
                <th className="px-3 py-2 font-semibold">Datasets</th>
                <th className="px-3 py-2 font-semibold">Score</th>
              </tr>
            </thead>
            <tbody>
              {results.map((r) => (
                <tr key={r.id} className="border-b border-border-col">
                  <td className="px-3 py-2 font-medium">{r.caption}</td>
                  <td className="px-3 py-2">{r.schema}</td>
                  <td className="px-3 py-2">
                    {(r.properties.country || [])
                      .map((c) => {
                        const country = countries.get(c.toUpperCase());
                        return country?.name?.common || c;
                      })
                      .join(", ") || "\u2014"}
                  </td>
                  <td className="px-3 py-2 text-xs">{r.datasets.join(", ")}</td>
                  <td className="px-3 py-2">{Math.round(r.score * 100)}%</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {/* VAT Result */}
      {screening.result_snapshot.vatResult && (
        <div className="mt-6">
          <h2 className="font-heading text-sm font-semibold uppercase text-text-secondary mb-2">
            VAT Verification
          </h2>
          <div className="rounded-md border border-border-col p-3 text-sm">
            <Badge variant={screening.result_snapshot.vatResult.valid ? "clear" : "warning"}>
              {screening.result_snapshot.vatResult.valid ? "VAT Verified" : "VAT Invalid"}
            </Badge>
            {screening.result_snapshot.vatResult.company_name && (
              <p className="mt-1">{screening.result_snapshot.vatResult.company_name}</p>
            )}
          </div>
        </div>
      )}

      {/* Datasets Checked */}
      <div className="mt-8 border-t border-border-col pt-4">
        <h2 className="font-heading text-sm font-semibold uppercase text-text-secondary mb-2">
          Datasets Checked ({datasets.length})
        </h2>
        <div className="grid grid-cols-2 gap-1 text-xs text-text-secondary">
          {datasets.map((ds) => (
            <span key={ds.name}>• {ds.title || ds.name}</span>
          ))}
        </div>
      </div>

      {/* Footer */}
      <div className="mt-8 border-t border-border-col pt-4 text-xs text-text-secondary">
        <p>
          Generated by AllClear on {new Date().toLocaleString()}. This report is a point-in-time
          screening and does not constitute legal advice. Sanctions data sourced from OpenSanctions.
        </p>
      </div>
    </div>
  );
}
